# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2020 Nuvoton technology corporation
#

obj-$(CONFIG_MA35D1_CLK_CCF) += clk_ma35d1.o
obj-$(CONFIG_MA35D0_CLK_CCF) += clk_ma35d0.o
obj-$(CONFIG_MA35H0_CLK_CCF) += clk_ma35h0.o

