# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2020 Nuvoton Technology Corp.
#

obj-y += pinctrl-nvt.o
obj-$(CONFIG_PINCTRL_MA35D1) += pinctrl-ma35d1.o
obj-$(CONFIG_PINCTRL_MA35H0) += pinctrl-ma35h0.o
obj-$(CONFIG_PINCTRL_MA35D0) += pinctrl-ma35d0.o
